### ISSUE TITLE
Preparing to onboard Akshar to Google Fonts

### ISSUE THREAD

**Issue by yanone** [tallchai/akshar-type#1]
Hello,

I'm reaching out to you here lacking another method of contact.

So I've been commissioned to onboard Akshar to Google Fonts, and for that I would like to ask you to fill this form providing us with some information about you: https://docs.google.com/forms/d/e/1FAIpQLSeMwHN8J213ZaxHrr5lHCrX56HY_NjGrWB8o604g98YxuMrdA/viewform

I will review the repository and possibly make some changes to the font, and will PR them back to you once finished.

Thank you
Yanone

**Comment by tallchai** [comment]
Hi @yanone 
Thanks for reaching out. I have filled out the GF Designer Profile.

I have the latest changes pushed to the [repo](https://github.com/tallchai/akshar-type). Looking forward to your changes. 👍🏽

**Comment by yanone** [comment]
Thank you.
For your information, onboarding Akshar requires the contrast axis that you used to be registered with the Google Fonts engineering team, as it's the first font to officially use it. This is a process of lengthy discussions, unfortunately, and will require some time. So while I have commenced the work, it is likely to take some time. I'll get back to you if I need anything. And I'm closing this issue for the meantime.

**Comment by tallchai** [comment]
@yanone 
I understand that the axis is not supported by Google Fonts right now.
But, we can publish the font without the contrast axis option until that axis gets supported by Google Fonts. In the meantime only the other axis (Weight) will show up on the font page.

Another possible option would be to publish the static, non-variable font files (until the support gets added) as two separate fonts: Akshar and Akshar Contrast.

The font's been in queue for over a year now and I believe we can atleast get it added to the directory. And add the variable/contrast-axis enhancement later. :)

**Comment by tallchai** [comment]
@yanone Hi 👋🏾
Checking back about the comment above.
We can update the font properties to meet the current Google Fonts setup.

**Comment by yanone** [comment]
Yes, we will publish it without the contrast axis at first and make an update once it's supported. The axis registration will be addressed this year and the contrast axis has a great chance of making it into the registry.

I'll start working on Akshar in the coming days.

**Comment by Anucha7736zxc** [comment]
> สวัสดี,
> 
> ฉันติดต่อคุณที่นี่โดยไม่มีวิธีการติดต่ออื่น
> 
> ดังนั้นฉันจึงได้รับมอบหมายให้เริ่มใช้งาน Akshar กับ Google Fonts และด้วยเหตุนี้ฉันจึงขอให้คุณกรอกแบบฟอร์มนี้เพื่อแจ้งข้อมูลบางอย่างเกี่ยวกับคุณ: [https://docs.google.com/forms/d/e/ 1FAIpQLSeMwHN8J213ZaxHrr5lHCrX56HY_NjGrWB8o604g98YxuMrdA/มุมมองฟอร์ม](https://docs.google.com/forms/d/e/1FAIpQLSeMwHN8J213ZaxHrr5lHCrX56HY_NjGrWB8o604g98YxuMrdA/viewform)
> 
> ฉันจะตรวจทานพื้นที่เก็บข้อมูลและอาจทำการเปลี่ยนแปลงบางอย่างกับแบบอักษร และจะตอบกลับคุณเมื่อเสร็จสิ้น
> 
> ขอบคุณ Yanone

**Comment by yanone** [comment]
Closing this issue as it's no longer needed. Thank you
